backend:
  name: github
  repo: james-wallis/ameira.me
  branch: master
publish_mode: editorial_workflow
media_folder: "/images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: "/images/portfolio"
    public_folder: ""
    editor:
     preview: false
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt"
        widget: "string"
      - label: "Date"
        name: "date"
        format: "YYYY-MM-DDTHH:mm"
        widget: "datetime"
        dateFormat: "DD/MM/YYYY"
        timeFormat: ""
      - {label: "Featured Image", name: "image", widget: "image"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["review"]
      - label: "Body"
        name: "body"
        widget: "markdown"
